### PR TITLE
Flux standard action

### PR DESCRIPTION
**Pull request by vzaidman**
changed the ambiguous "meta" property name to a clearer property name.

meta is confusing because it's hard to tell from the name what's its purpose.

### CODE REVIEW

**Review by arikmaor — APPROVED** [review]

**Comment by pke** [comment]
Approved but not merged? @ArikMaor

**Comment by vzaidman** [comment]
@pke ill do it this week, i hope

**Comment by gontard** [comment]
Any news ? This pull request is important for me too.

**Comment by vzaidman** [comment]
published to npm as `redux-undo-redo@1.2.0-rc.1`

this will be merged to master when we will have the chance to update the syntax in our application as well

**Pull request merged**
